// AUTO-GENERATED by agent/generate_tests.py
// Source feature file: backend-app/routes/api/articles.js
// Focus: comment creation and deletion
// Model: claude-sonnet-5
//
// PROVENANCE NOTE (read this before treating this as a normal agent run):
// This particular file was NOT produced by executing generate_tests.py,
// because the sandbox this was built in has no ANTHROPIC_API_KEY and no
// route to the Anthropic API with credentials. Instead, this file was
// produced by hand-simulating exactly what the agent's system prompt asks
// for: reading only routes/api/articles.js (not models/comment.js or
// models/user.js - the agent was never shown those), and applying the same
// grounding rules verbatim. Running `python agent/generate_tests.py
// --feature-file backend-app/routes/api/articles.js --focus "comment
// creation and deletion" --out agent/output/comments.generated.spec.ts`
// with a real key reproduces this mechanically (model output will vary
// slightly run to run, but should follow the same structure and the same
// test.fixme for the author-shape gap noted below).
//
// GROUNDING CHECK: PASSED
//   - POST   /api/articles/:article/comments           -> matches router.post('/:article/comments', ...)
//   - DELETE /api/articles/:article/comments/:comment   -> matches router.delete('/:article/comments/:comment', ...)
//   - 403 on delete-by-non-author asserted from:
//       if (author.id.toString() === req.payload.id.toString()) { ... } else { res.sendStatus(403) }
//   - 204 on successful delete asserted from: req.comment.destroy().then(() => res.sendStatus(204))
//   - comment.body assertion is grounded: the route does
//       Comment.create(Object.assign({}, req.body.comment, { articleId, authorId }))
//     so the created comment's body is exactly what the test sent as req.body.comment.body.

import { test, expect } from '@playwright/test';

function uniqueUser() {
  const id = Date.now() + '-' + Math.floor(Math.random() * 1e6);
  return {
    username: `tester_${id}`,
    email: `tester_${id}@example.com`,
    password: 'correct horse battery staple',
  };
}

async function registerAndGetToken(request: import('@playwright/test').APIRequestContext) {
  const user = uniqueUser();
  const res = await request.post('/api/users', { data: { user } });
  const body = await res.json();
  return body.user.token as string;
}

async function createArticle(request: import('@playwright/test').APIRequestContext, token: string) {
  const res = await request.post('/api/articles', {
    headers: { Authorization: `Token ${token}` },
    data: {
      article: {
        title: `Comments target ${Date.now()}`,
        description: 'article to comment on',
        body: 'body',
      },
    },
  });
  const { article } = await res.json();
  return article;
}

test.describe('Article comments (routes/api/articles.js)', () => {
  test('an authenticated user can post a comment, and the response echoes the submitted body', async ({ request }) => {
    const authorToken = await registerAndGetToken(request);
    const article = await createArticle(request, authorToken);

    const commenterToken = await registerAndGetToken(request);
    const commentBody = 'A grounded comment body.';
    const res = await request.post(`/api/articles/${article.slug}/comments`, {
      headers: { Authorization: `Token ${commenterToken}` },
      data: { comment: { body: commentBody } },
    });

    expect(res.ok(), await res.text()).toBeTruthy();
    const { comment } = await res.json();
    // Grounded: the route builds the comment directly from req.body.comment,
    // so body must be exactly what we sent.
    expect(comment.body).toBe(commentBody);
    expect(comment.id).toBeDefined();
  });

  test.fixme(
    "comment.author reflects the commenting user's profile fields (username/bio/image/following)",
    async () => {
      // NOT WRITTEN: the agent was only given routes/api/articles.js. The
      // comment's author is serialized by Comment.toJSONFor -> User's
      // toProfileJSONFor (models/comment.js, models/user.js), neither of
      // which was in the feature file the agent read. Asserting on
      // comment.author.username or comment.author.following here would be a
      // guess dressed up as a grounded test. Show the agent models/user.js
      // and models/comment.js and re-run to get this test for real.
    }
  );

  test('deleting a comment as someone other than its author is rejected with 403', async ({ request }) => {
    const authorToken = await registerAndGetToken(request);
    const article = await createArticle(request, authorToken);

    const commenterToken = await registerAndGetToken(request);
    const commentRes = await request.post(`/api/articles/${article.slug}/comments`, {
      headers: { Authorization: `Token ${commenterToken}` },
      data: { comment: { body: 'a comment' } },
    });
    const { comment } = await commentRes.json();

    // A third, unrelated user tries to delete someone else's comment.
    const attackerToken = await registerAndGetToken(request);
    const deleteRes = await request.delete(`/api/articles/${article.slug}/comments/${comment.id}`, {
      headers: { Authorization: `Token ${attackerToken}` },
    });

    // Grounded in: `if (author.id.toString() === req.payload.id.toString()) {...} else { res.sendStatus(403) }`
    expect(deleteRes.status()).toBe(403);
  });

  test('deleting your own comment succeeds and removes it', async ({ request }) => {
    const authorToken = await registerAndGetToken(request);
    const article = await createArticle(request, authorToken);

    const commenterToken = await registerAndGetToken(request);
    const commentRes = await request.post(`/api/articles/${article.slug}/comments`, {
      headers: { Authorization: `Token ${commenterToken}` },
      data: { comment: { body: 'delete me' } },
    });
    const { comment } = await commentRes.json();

    const deleteRes = await request.delete(`/api/articles/${article.slug}/comments/${comment.id}`, {
      headers: { Authorization: `Token ${commenterToken}` },
    });
    // Grounded in: req.comment.destroy().then(() => res.sendStatus(204))
    expect(deleteRes.status()).toBe(204);

    // And it should no longer show up in the comment list.
    const listRes = await request.get(`/api/articles/${article.slug}/comments`);
    const { comments } = await listRes.json();
    expect(comments.find((c: { id: number }) => c.id === comment.id)).toBeUndefined();
  });
});
